### YamlMime:Landing
title: Kubernetes con abilitazione di Azure Arc (anteprima)
summary: Informazioni su come gestire i cluster Kubernetes con Azure Arc
metadata:
  title: Kubernetes con abilitazione di Azure Arc
  description: Informazioni su come gestire i computer locali in Azure
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 02/15/2021
  ms.author: shasb
  ms.openlocfilehash: 97343e8c23e202e70ec30bb0a522105889ea08b3
  ms.sourcegitcommit: de98cb7b98eaab1b92aa6a378436d9d513494404
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 02/17/2021
  ms.locfileid: "100560245"
landingContent:
- title: Connettere i cluster Kubernetes ad Azure con Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Che cos'è Kubernetes con abilitazione di Azure Arc?
      url: overview.md
  - linkListType: concept
    links:
    - text: Architettura degli agenti
      url: conceptual-agent-architecture.md
    - text: Configurazioni e GitOps
      url: conceptual-configurations.md
    - text: Domande frequenti
      url: faq.md
- title: Introduzione
  linkLists:
  - linkListType: quickstart
    links:
    - text: Connettere il cluster
      url: connect-cluster.md
- title: Configurare, gestire e monitorare i cluster
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Distribuire configurazioni con GitOps
      url: use-gitops-connected-cluster.md
    - text: Distribuire grafici Helm con GitOps
      url: use-gitops-with-helm.md
    - text: Applicare GitOps con Criteri di Azure
      url: use-azure-policy.md
    - text: Distribuire i carichi di lavoro Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Modello di verifica
  linkLists:
  - linkListType: sample
    links:
    - text: Jumpstart
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Architettura di riferimento
  linkLists:
  - linkListType: architecture
    links:
    - text: Gestire distribuzioni e configurazioni per i cluster Kubernetes ibridi
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
