### YamlMime:Landing
title: Kubernetes con abilitazione di Azure Arc
summary: Azure Arc estende le funzionalità di Azure Resource Manager ai cluster Kubernetes in qualsiasi infrastruttura locale, multicloud e perimetrale.
metadata:
  title: Kubernetes con abilitazione di Azure Arc
  description: Informazioni su come gestire i cluster Kubernetes
  author: mlearned
  manager: carmonm
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 05/19/2020
  ms.author: mlearned
  ms.openlocfilehash: 80f3faa93315d5c20c2e1876cb46f7771433969d
  ms.sourcegitcommit: 23604d54077318f34062099ed1128d447989eea8
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 06/20/2020
  ms.locfileid: "85117693"
landingContent:
- title: Panoramica di Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Altre informazioni su Azure Arc
      url: https://azure.microsoft.com/services/azure-arc/
- title: Connettere i cluster Kubernetes ad Azure con Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Che cos'è Kubernetes con abilitazione di Azure Arc?
      url: ./overview.md
  - linkListType: how-to-guide
    links:
    - text: Connettere il cluster
      url: ./connect-cluster.md
    - text: Usare GitOps in un cluster connesso
      url: ./use-gitops-connected-cluster.md
    - text: Usare GitOps con Helm
      url: ./use-gitops-with-helm.md
    - text: Usare Monitoraggio di Azure per i contenitori
      url: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md
    - text: Usare Criteri di Azure
      url: ./use-azure-policy.md
    - text: Distribuire i carichi di lavoro Azure IoT Edge
      url: ./deploy-azure-iot-edge-workloads.md
    - text: Entità servizio di onboarding
      url: ./create-onboarding-service-principal.md
